### ISSUE TITLE
ERROR  "Optimizations failure" while installing sense

### ISSUE THREAD

**Issue by zhaowai** [elastic/sense#113]
I get the following error message while trying to install the sense on kibana 4.40. 

BTW, I have downloaded the zip file of sense from github and then put the zip file on the server before try to install.

```
[root@JTJKAPP14571-DT/cpic/els/kibana]#bin/kibana plugin --install sense --url file:///cpic/els/sense-master.zip
Installing sense
Attempting to transfer from file:///cpic/els/sense-master.zip
Transferring 2492225 bytes....................
Transfer complete
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "Optimizations failure.
    ERROR in ./installedPlugins/sense/public/sense.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /cpic/els/kibana/src/ui/public/autoload/styles in /cpic/els/kibana/installedPlugins/sense/public
     @ ./installedPlugins/sense/public/sense.js 8:0-29
"
```

How can I go through this issue? 

TIA.

Jerry Zhao

**Comment by spalger** [comment]
Sense can't be installed from github, it must be installed from the distributed "built" version, which you can make using the github repository or by downloading from here: https://download.elastic.co/elastic/sense/sense-latest.tar.gz

**Comment by shr269** [comment]
i have downloaded kibana from the official elastic product page. Trying to install sense. Getting the below error. please help.

C:\DEV\kibana\bin>kibana plugin --install elastic/sense
Installing sense
Attempting to transfer from https://download.elastic.co/elastic/sense/sense-latest.ta
r.gz
Error: Client request error: connect ETIMEDOUT 184.73.171.50:443
Plugin installation was unsuccessful due to error "Client request error: connect ETIM
EDOUT 184.73.171.50:443"
