### ISSUE TITLE
Sense Chrome Extension flagged as malware

### ISSUE THREAD

**Issue by spdesai** [elastic/sense#166]
The Sense extension is getting flagged as malware in Chrome.  
![image](https://user-images.githubusercontent.com/1816427/32199884-a4d6cab2-bd9c-11e7-8a7b-3047d51f5d83.png)

**Comment by estein-de** [comment]
But, what malware one wonders...

**Comment by bleskes** [comment]
@spdesai thanks for the notice. This repo is not maintained anymore. Sense is now part of Kibana and is called Console.

**Comment by spdesai** [comment]
Thanks for the update!

**Comment by stellamargonar** [comment]
Why why why why  did you stop maintaining it?  Sense in Kibana does not support all the features that the chrome plugin used to.

For example, in my work i have to use a local index (with a small subset of data), and different remotes indexes with full set of data.
With the chrome plugin i could run the same query on my local index for dev/test ecc, and then run it again on the production cluster, just changing the url in the top text field, or in the request line.

Since the plugin is not available anymore i installed a local kibana for my test data, and every time i want to run the same query on a remote index i have to stop kibana -> change the conf -> start kibana (because we don't have, and we don't want, a kibana instance running on the production cluster).

Yes i can do this trick and everything still works, i could copy the query in another REST client and the result would be the same, but me and a lot of my collegues found your plugin (a bit buggy) but very useful and helpful for our work.

**Comment by SamCritch** [comment]
Yeah, I just ran into this problem as well... I can use the "Elasticsearch HEAD" extension, but it's not as handy as Sense.

**Comment by StephaneBour** [comment]
Hi,

You can find my fork of this extension here :
https://github.com/StephaneBour/sense-chrome ;-)

**Comment by pjohnson-ptc** [comment]
@StephaneBour  - Thanks for this.  It's a great help, since  Elastic Kibana (old versions especially were much less intuitive)

**Comment by AhmedHelalAhmed** [comment]
thanks
