### ISSUE TITLE
sense offline install

### ISSUE THREAD

**Issue by sdba2** [elastic/sense#74]
how to manually (offline) install sense.
what do i need to download and what are the command/s to install ?

**Comment by bleskes** [comment]
heya. See https://www.elastic.co/guide/en/sense/current/installing.html#manual_download 

Let me know if doesn't work...

**Comment by sdba2** [comment]
first, thanks for the quick response.
i am working on windows machine
kibana is up and running
i have download the file and unziped the file
then i tried to run the following commands :

     cd c:\elasticsearch\kibana-4.2.0-windows\bin

     kibana plugin -i sense -u file:/C:\Temp\sense-2.0.0-beta1.tar.gz
     kibana plugin -i sense -u file:/C:\Temp\sense-2.0.0-beta1.tar

on both tries i get the same error :
INFO: Could not find files for the given pattern(s).
Installing sense
Attempting to extract from file:/C:\Temp\sense-2.0.0-beta1.tar.gz
Error: ENOENT, open 'c:\C:\Temp\sense-2.0.0-beta1.tar.gz'
Plugin installation was unsuccessful due to error "Not a valid url."

**Comment by bleskes** [comment]
I think you miss and extra slash after the file: - i.e., `file://C:...`

**Comment by sdba2** [comment]
you're right!
it's working

thanks

**Comment by daguero** [comment]
hello
I'm trying to install plugins in Kibana sense, I use a docker Kibana image to run, but I can not do it, this is the idea that I have to do this:
  kibana plugin --install sense --url file:///tmp/sense-2.0.0-beta5.tar.gz

But I get the following error:
Error: ENOTFOUND
Plugin installation was unsuccessful due to error "No valid url specified."

Any idea what happens to me...

**Comment by daguero** [comment]
Problem solved

**Comment by TonyMF** [comment]
Thanks Boaz... it worked.

C:\Software\Elastic>C:\Software\Elastic\kibana-4.5.0-windows\bin\kibana plugin -i sense -u **file://**C:/Software/Elastic/sense-2.0.0-beta5
.tar.gz
Installing sense
Attempting to transfer from file://C:/Tony/Software/Elastic/sense-2.0.0-beta5.tar.gz
Transferring 1352402 bytes....................
Transfer complete
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation complete

**Comment by shr269** [comment]
i have downloaded kibana from the official elastic product page. Trying to install sense. Getting the below error. please help.

C:\DEV\kibana\bin>kibana plugin --install elastic/sense
Installing sense
Attempting to transfer from https://download.elastic.co/elastic/sense/sense-latest.ta
r.gz
Error: Client request error: connect ETIMEDOUT 184.73.171.50:443
Plugin installation was unsuccessful due to error "Client request error: connect ETIM
EDOUT 184.73.171.50:443"

**Comment by mgunjan** [comment]
thanks a lot for the post. I was working on ubuntu vm behind proxy . I was able to install sense using offline method.
